### ISSUE TITLE
Create Comment fails with error in MailgunSubscriber

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#366]
I wanted to create a comment on a report and got the following error:

```
Fatal error: Uncaught Error: Call to a member function calendarWeek() on null in /var/www/src/Notification/MailgunSubscriber.php:82 Stack trace:
#0 /var/www/src/Notification/NotificationService.php(27): 
Jimdo\Reports\Notification\MailgunSubscriber->notify(Object(Jimdo\Reports\Notification\Events\CommentCreated))
#1 /var/www/src/Application/ApplicationService.php(253): 
Jimdo\Reports\Notification\NotificationService->notify(Object(Jimdo\Reports\Notification\Events\CommentCreated))
#2 /var/www/src/Web/Controller/CommentController.php(60):
Jimdo\Reports\Application\ApplicationService->createComment('58b3db0c53e0b', '58aac1245c25a', '09.03.2017 15:2...', '<p>Das ist <i>n...')
#3 /var/www/src/Web/Router.php(117):
Jimdo\Reports\Web\Controller\CommentController->createCommentAction()
#4 /var/www/app/router.php(15):
Jimdo\Reports\Web\Router->dispatch('/comment/create...')
#5 {main} thrown in /var/www/src/Notification/MailgunSubscriber.php on line 82
```

**Comment by SharktheFire** [comment]
Implemented in #373
